#---------------------------------#
# general configuration #
#---------------------------------#

# version format
version: 0.0.0.1.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

#---------------------------------#
# environment configuration #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# clone directory
clone_folder: c:\projects\sudo


#---------------------------------#
# build configuration #
#---------------------------------#

build_script:
  - cmd: build.bat

# to disable automatic builds
build: off


#---------------------------------#
# artifacts configuration #
#---------------------------------#

artifacts:
  - path: bin
  - name: sudo-in-windows
  - type: zip
